spring.application.name=taskflow-backend

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:taskflow
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show generated SQL in logs so you can learn from it (Block 3)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 web console at http://localhost:8080/h2-console
spring.h2.console.enabled=true

server.port=8080
